version: '3'

# ====================================================================================================================
# POSTGRES SERVER
# ====================================================================================================================
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: meuusuario
      POSTGRES_PASSWORD: minhasenha
      POSTGRES_DB: meubanco
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data

# ====================================================================================================================
# PGADMIN
# ====================================================================================================================
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.com
      - PGADMIN_DEFAULT_PASSWORD=password
    depends_on:
      - db